import { Concert, Step } from "./types";

export const STEPS: Step[] = [
  {
    id: 1,
    title: "Choose Concert",
    subtitle: "Select your K-POP artist & show",
    icon: "🎵",
    color: "from-blue-500 to-indigo-600",
    bgColor: "bg-blue-500/10",
  },
  {
    id: 2,
    title: "Account Setup",
    subtitle: "Verify your ticketing account",
    icon: "👤",
    color: "from-sky-400 to-blue-600",
    bgColor: "bg-sky-500/10",
  },
  {
    id: 3,
    title: "Fan Club",
    subtitle: "Register for pre-sale access",
    icon: "💜",
    color: "from-cyan-500 to-teal-600",
    bgColor: "bg-cyan-500/10",
  },
  {
    id: 4,
    title: "Queue",
    subtitle: "Enter the virtual waiting room",
    icon: "⏳",
    color: "from-blue-600 to-sky-500",
    bgColor: "bg-blue-600/10",
  },
  {
    id: 5,
    title: "Seat Selection",
    subtitle: "Pick your perfect spot",
    icon: "💺",
    color: "from-teal-500 to-cyan-500",
    bgColor: "bg-teal-500/10",
  },
  {
    id: 6,
    title: "Payment",
    subtitle: "Complete your purchase",
    icon: "💳",
    color: "from-indigo-500 to-blue-700",
    bgColor: "bg-indigo-500/10",
  },
];

export const CONCERTS: Concert[] = [
  {
    id: "bts-2025",
    artist: "BTS",
    artistKr: "방탄소년단",
    tour: "5TH MUSTER: MAGIC SHOP 2025",
    date: "2025.08.15 ~ 08.17",
    venue: "Seoul Olympic Stadium",
    venueKr: "서울올림픽주경기장",
    city: "Seoul, Korea",
    image: "🎤",
    difficulty: "Extreme",
    platform: "Weverse Shop",
  },
  {
    id: "blackpink-2025",
    artist: "BLACKPINK",
    artistKr: "블랙핑크",
    tour: "BORN PINK WORLD TOUR: ENCORE",
    date: "2025.09.06 ~ 09.07",
    venue: "KSPO DOME",
    venueKr: "KSPO돔",
    city: "Seoul, Korea",
    image: "🌸",
    difficulty: "Hard",
    platform: "Melon Ticket",
  },
  {
    id: "aespa-2025",
    artist: "aespa",
    artistKr: "에스파",
    tour: "SYNK: PARALLEL LINE WORLD TOUR",
    date: "2025.10.11 ~ 10.12",
    venue: "Gocheok Sky Dome",
    venueKr: "고척스카이돔",
    city: "Seoul, Korea",
    image: "⚡",
    difficulty: "Hard",
    platform: "Interpark Ticket",
  },
  {
    id: "seventeen-2025",
    artist: "SEVENTEEN",
    artistKr: "세븐틴",
    tour: "RIGHT HERE WORLD TOUR 2025",
    date: "2025.11.15 ~ 11.16",
    venue: "Seoul World Cup Stadium",
    venueKr: "서울월드컵경기장",
    city: "Seoul, Korea",
    image: "💎",
    difficulty: "Extreme",
    platform: "YES24 Live",
  },
];

export const AI_TIPS: Record<number, string[]> = {
  1: [
    "Check the official artist fan café or Weverse for concert announcements",
    "Different concerts use different ticketing platforms — know yours beforehand",
    "Mark your calendar: Korean tickets often sell out in under 5 minutes",
    "'극한직업 (Extreme difficulty)' means even locals struggle to get tickets!",
  ],
  2: [
    "Create your ticketing account WEEKS before the sale — verification takes time",
    "Korean platforms require phone verification (SMS) — have a Korean number or use a USIM",
    "Your name on the account must match your passport exactly",
    "Some platforms require a Korean resident registration number — foreigners can use their passport number",
  ],
  3: [
    "Fan club membership (팬클럽) usually gives you pre-sale access 1-2 days early",
    "ARMY Membership, BLINK Membership etc. have annual fees (~₩30,000)",
    "Pre-sale queues are less chaotic — join the fan club!",
    "Fan club registration deadlines are usually 2-3 months before the concert",
  ],
  4: [
    "The queue opens exactly at the announced time — be ready 10 minutes early",
    "Do NOT refresh your browser once in the queue — you'll lose your spot!",
    "Queue positions are randomized at start time, not first-come-first-served",
    "Keep the browser tab active — going to sleep mode may disconnect you",
  ],
  5: [
    "You have only 5-10 minutes to select and hold your seat",
    "GA Pit (스탠딩) = best experience but very competitive",
    "If your preferred section is sold out, check adjacent sections immediately",
    "Click fast — seats appear available but may already be held by others",
  ],
  6: [
    "Have your payment method ready BEFORE entering the queue",
    "Korean cards process fastest — foreign cards sometimes fail",
    "KakaoPay and Naver Pay work well for foreigners with Korean bank accounts",
    "You have only 10 minutes to complete payment after selecting seats",
  ],
};
